# Generated by Django 2.2.16 on 2022-10-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
